// Nightly horoscope publishing, shared by the server's built-in scheduler
// and the manual CLI (scripts/generate-daily-horoscope.js).
//
// Content source per (day, rashi), in order: Gemini (when GEMINI_API_KEY is
// set, with one retry) → yesterday's row for the same rashi (stale beats
// broken) → the per-rashi sample in the experiment config. Publishing never
// fails, so a missing row can only mean "not generated yet".
//
// Concurrency: an advisory transaction lock keyed on (day, rashi) serializes
// simultaneous publishes from any number of pods; the existence check inside
// the lock makes re-runs no-ops.
import { query, withTx } from './db.js';
import { todayKey, nextDayKey, nextResetAt } from './day.js';
import { transitFacts } from './transit.js';
import { geminiEnabled, generateWithGemini } from './gemini.js';

async function fetchRecentReadings(cfg, day, rashi) {
  const { rows } = await query(
    `SELECT today_reading FROM horoscopes
      WHERE rashi = $1 AND day < $2 AND day >= ($2::date - $3::int)
      ORDER BY day DESC`,
    [rashi, day, cfg.recentReadingDays ?? 3],
  );
  return rows.map((r) => r.today_reading);
}

async function fetchPreviousRow(day, rashi) {
  const { rows } = await query(
    `SELECT mood, lucky_number, lucky_time, lucky_colours, today_reading, domain_insights
       FROM horoscopes WHERE rashi = $1 AND day < $2 ORDER BY day DESC LIMIT 1`,
    [rashi, day],
  );
  return rows[0] || null;
}

async function fetchYesterdayLuck(day, rashi) {
  const prev = await fetchPreviousRow(day, rashi);
  if (!prev) return null;
  return `number ${prev.lucky_number}, time ${prev.lucky_time}, colours ${prev.lucky_colours.join('/')}`;
}

async function generateContent(cfg, day, rashi, facts) {
  if (geminiEnabled()) {
    try {
      const [recent, avoid] = await Promise.all([
        fetchRecentReadings(cfg, day, rashi),
        fetchYesterdayLuck(day, rashi),
      ]);
      const content = await generateWithGemini(cfg, facts, recent, avoid);
      console.log(`[horoscope] ${day}/${rashi}: content generated by Gemini`);
      return { content, source: 'gemini' };
    } catch (err) {
      console.error(`[horoscope] ${day}/${rashi}: Gemini failed twice (${err.message}), falling back`);
      const previous = await fetchPreviousRow(day, rashi);
      if (previous) {
        console.log(`[horoscope] ${day}/${rashi}: re-serving the previous day's reading`);
        return { content: previous, source: 'fallback-previous' };
      }
    }
  } else {
    console.log(`[horoscope] ${day}/${rashi}: GEMINI_API_KEY not set, using config sample`);
  }
  return { content: cfg.sampleHoroscopes[rashi], source: 'sample' };
}

export async function publishHoroscope(cfg, day, rashi, { force = false } = {}) {
  // Compute facts and generate BEFORE opening the transaction — Gemini can
  // take many seconds and must not hold DB locks while it thinks.
  const facts = transitFacts(cfg, day, rashi);
  const { content, source } = await generateContent(cfg, day, rashi, facts);

  return withTx(async (client) => {
    await client.query('SELECT pg_advisory_xact_lock(hashtext($1))', [`horoscope-${day}-${rashi}`]);

    const existing = await client.query(
      'SELECT 1 FROM horoscopes WHERE day = $1 AND rashi = $2', [day, rashi],
    );
    if (existing.rowCount > 0) {
      if (!force) return { published: false, reason: 'exists' };
      await client.query('DELETE FROM horoscopes WHERE day = $1 AND rashi = $2', [day, rashi]);
      console.log(`[horoscope] --force: replaced ${day}/${rashi}`);
    }

    await client.query(
      `INSERT INTO horoscopes
         (day, rashi, mood, lucky_number, lucky_time, lucky_colours,
          today_reading, domain_insights, transit_facts, source)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,
      [
        day, rashi, content.mood, content.lucky_number, content.lucky_time,
        JSON.stringify(content.lucky_colours), content.today_reading,
        JSON.stringify(content.domain_insights), JSON.stringify(facts), source,
      ],
    );
    console.log(`[horoscope] published ${day}/${rashi} (${source})`);
    return { published: true, source };
  });
}

export async function fetchHoroscope(day, rashi) {
  const { rows } = await query(
    `SELECT day, rashi, mood, lucky_number, lucky_time, lucky_colours,
            today_reading, domain_insights, source
       FROM horoscopes WHERE day = $1 AND rashi = $2`,
    [day, rashi],
  );
  return rows[0] || null;
}

// Cheap idempotent per-rashi guard used on the request path: after the first
// success for a given (day, rashi) it costs nothing (in-memory check); at the
// 06:00 IST rollover it publishes the new day's row exactly once even under
// concurrent callers.
const ensured = new Map(); // rashi -> day
const inflight = new Map(); // rashi -> promise

export async function ensureRashiForToday(cfg, rashi) {
  const day = todayKey();
  if (ensured.get(rashi) === day) return day;
  if (!inflight.get(rashi)) {
    inflight.set(rashi, (async () => {
      const existing = await fetchHoroscope(day, rashi);
      if (!existing) await publishHoroscope(cfg, day, rashi);
      ensured.set(rashi, day);
    })().finally(() => inflight.delete(rashi)));
  }
  await inflight.get(rashi);
  return day;
}

export async function publishAll(cfg, day, opts = {}) {
  // Sequential on purpose: at most 12 polite Gemini calls, not a burst.
  // The existence pre-check keeps the recurring server tick free once the
  // day's batch is in — generation only happens for missing rows.
  for (const r of cfg.rashis) {
    if (!opts.force && await fetchHoroscope(day, r.key)) continue;
    await publishHoroscope(cfg, day, r.key, opts);
  }
}

// Nightly pre-generation: within HOROSCOPE_PREGEN_HOURS of the 06:00 IST
// cutover (i.e. during the night), publish TOMORROW's batch ahead of time so
// the cutover flips onto content that already exists instead of making the
// first 06:00 visitor wait on a Gemini call. Advisory lock + existence check
// make any number of pods safe here.
const PREGEN_WINDOW_MS = Number(process.env.HOROSCOPE_PREGEN_HOURS ?? 4) * 3_600_000;
let pregeneratedDay = null;

export async function ensureUpcoming(cfg) {
  if (!(PREGEN_WINDOW_MS > 0)) return null;
  const now = new Date();
  if (nextResetAt(now).getTime() - now.getTime() > PREGEN_WINDOW_MS) return null;
  const day = nextDayKey(todayKey(now));
  if (pregeneratedDay === day) return day;
  console.log(`[horoscope] nightly pre-generation for ${day}`);
  await publishAll(cfg, day);
  pregeneratedDay = day;
  return day;
}
